# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63551da335e4782fb26200f211c4de1e27e9f804899eb5b2f5075e316c10e62f20c3d091abb28e5df6bca57159d0e7a948784e3dea8047c1c54427adc083ec3b

test:
  secret_key_base: fd16756e7e72e427924ebb5b01992315611cfdaee46ac7867e92d15a579afdef385665874fdf523f8b26d5086d58c92d9a8ebd71673070bdaf49c1e0a54dd40c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
